spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: team_d
    password: green502
    url: jdbc:mariadb://192.168.0.144:3306/team_d

mybatis:
  type-aliases-package: com.team.winey
  mapper-locations: mapper/*.xml

springdoc:
  swagger-ui:
    path: /swagger.html

file:
  dir: /home/download

---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:mariadb://localhost:3306/test
  sql:
    init:
      mode: always
      schema-locations: init/schema.sql
      data-locations: init/data.sql